// Seed data: the parking areas on the ANU Acton campus.
//
// GENERATED FROM OPENSTREETMAP. Every entry is a distinct parking feature that
// OpenStreetMap records inside the Acton campus (© OpenStreetMap
// contributors): amenity=parking (and amenity=motorcycle_parking for the
// two-wheel bays), de-duplicated so a lot mapped as both a relation and its
// member ways appears once. Each entry's lat/lng is the centre of that feature,
// the same data the map draws, so every pin sits on a real mapped lot. Capacity
// and accessible-bay counts are shown only where OSM records them.
//
// CLIPPED TO THE CAMPUS. The set is bounded by the roads that ring Acton:
// Clunies Ross Street (west), Barry Drive (north) and Edinburgh Avenue
// (south-east). Lots the OSM extract caught across those roads (CSIRO Black
// Mountain and the Botanic Gardens, North Oval and Toad Hall, New Acton) are
// not on this campus and are left out. The boundary is traced from the roads'
// own OSM geometry; see the CAMPUS_BOUNDARY note in scripts/gen-parking.mjs.
//
// RATES are ANU's published 2026 parking fees — staff surface $7.78/day,
// staff parking stations $9.59/day, non-resident student $3.88/day, resident
// student $4.90/day, free for accessible-permit and motorbike users, pay/permit
// zones enforced 8am–5pm Mon–Fri and free after 5pm and on weekends.
// Source: https://services.anu.edu.au/campus-environment/transport-parking/parking-fees
//
// THE INTERPRETIVE LAYER, not surveyed: the CATEGORY, RATE and PERMIT of each
// lot are derived from its OSM access/fee/type tags mapped onto the ANU scheme
// above (e.g. access=private → resident/private; access=permit → permit zone;
// public + fee → visitor pay; otherwise the campus staff/student surface
// default). Lot NAMES without an OSM name are labelled by the nearest mapped
// landmark. This is a reasonable reading of open data, not a lot-by-lot check of
// the signage; the README and the app's footnote say so.
//
// To regenerate after refreshing the OSM extracts, see scripts/gen-parking.mjs.

export type Seed = {
  slug: string;
  name: string;
  category: string;
  lat: number;
  lng: number;
  hours: string;
  rate: string;
  permit: string;
  fees: string;
  notes?: string;
  capacity?: number;
};

export const CAR_PARKS: Seed[] = [
  {
    slug: "surface-parking-near-anu-college-of-law-building-3",
    name: "Surface parking near ANU College of Law - Building 5 Foyer",
    category: "Customer parking",
    lat: -35.28127,
    lng: 149.12016,
    hours: "While attending the adjacent facility.",
    rate: "For patrons of the adjacent facility; check the on-site signage.",
    permit: "Customers of the adjacent facility.",
    fees: "OSM access: customers. Fee: yes. Type: surface.",
    notes: "Beside ANU College of Law - Building 5 Foyer. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-anu-medical-school",
    name: "Surface parking near ANU Medical School",
    category: "Free parking",
    lat: -35.28305,
    lng: 149.11454,
    hours: "Available at all times.",
    rate: "Free.",
    permit: "None.",
    fees: "OSM records no access restriction. Fee: no. Type: surface.",
    notes: "Beside ANU Medical School. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-fses-field-services",
    name: "Surface parking near FSES Field Services",
    category: "Free parking",
    lat: -35.27808,
    lng: 149.11825,
    hours: "Available at all times.",
    rate: "Free.",
    permit: "None.",
    fees: "OSM access: yes. Fee: no. Type: surface.",
    notes: "Beside FSES Field Services. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-university-house",
    name: "Surface parking near University House",
    category: "Free parking",
    lat: -35.2843,
    lng: 149.1186,
    hours: "Available at all times.",
    rate: "Free.",
    permit: "None.",
    fees: "OSM access: yes. Fee: no. Type: surface.",
    notes: "Beside University House. asphalt surface. Mapped in OpenStreetMap.",
  },
  {
    slug: "motorcycle-parking-near-anu-college-of-law-build",
    name: "Motorcycle parking near ANU College of Law - Building 5 Foyer",
    category: "Motorbike parking",
    lat: -35.281,
    lng: 149.11934,
    hours: "Available at all times.",
    rate: "Free for motorbikes and scooters.",
    permit: "None required for motorbikes and scooters.",
    fees: "OSM access: permit.",
    notes: "Beside ANU College of Law - Building 5 Foyer. Mapped in OpenStreetMap.",
    capacity: 3,
  },
  {
    slug: "surface-parking-near-anu-college-of-law-building-4",
    name: "Surface parking near ANU College of Law - Building 5 Foyer",
    category: "Permit parking",
    lat: -35.28159,
    lng: 149.11929,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit zone. 2026 rates by permit: staff surface $7.78/day, staff parking station $9.59/day, student $3.88/day, resident $4.90/day.",
    permit: "A valid ANU permit for this zone.",
    fees: "OSM access: permit. Type: surface.",
    notes: "Beside ANU College of Law - Building 5 Foyer. asphalt surface. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-anu-college-of-law-building-5",
    name: "Surface parking near ANU College of Law - Building 6A - Moot Court",
    category: "Permit parking",
    lat: -35.27991,
    lng: 149.11895,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit zone. 2026 rates by permit: staff surface $7.78/day, staff parking station $9.59/day, student $3.88/day, resident $4.90/day.",
    permit: "A valid ANU permit for this zone.",
    fees: "OSM access: permit. Type: surface.",
    notes: "Beside ANU College of Law - Building 6A - Moot Court. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-anu-school-of-music",
    name: "Surface parking near ANU School of Music",
    category: "Permit parking",
    lat: -35.28033,
    lng: 149.12324,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit zone. 2026 rates by permit: staff surface $7.78/day, staff parking station $9.59/day, student $3.88/day, resident $4.90/day.",
    permit: "A valid ANU permit for this zone.",
    fees: "OSM access: permit. Fee: no. Type: surface.",
    notes: "Beside ANU School of Music. asphalt surface. 3 marked accessible bays. Mapped in OpenStreetMap.",
    capacity: 37,
  },
  {
    slug: "surface-parking-near-ian-ross-building-31",
    name: "Surface parking near Ian Ross Building - 31",
    category: "Permit parking",
    lat: -35.27581,
    lng: 149.12031,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit zone. 2026 rates by permit: staff surface $7.78/day, staff parking station $9.59/day, student $3.88/day, resident $4.90/day.",
    permit: "A valid ANU permit for this zone.",
    fees: "OSM access: permit. Type: surface.",
    notes: "Beside Ian Ross Building - 31. asphalt surface. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-peter-karmel-building",
    name: "Surface parking near Peter Karmel Building",
    category: "Permit parking",
    lat: -35.27966,
    lng: 149.12389,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit zone. 2026 rates by permit: staff surface $7.78/day, staff parking station $9.59/day, student $3.88/day, resident $4.90/day.",
    permit: "A valid ANU permit for this zone.",
    fees: "OSM access: permit. Type: surface.",
    notes: "Beside Peter Karmel Building. asphalt surface. 5 marked accessible bays. Mapped in OpenStreetMap.",
    capacity: 66,
  },
  {
    slug: "multi-storey-parking-near-unilodge-davey-lodge",
    name: "Multi-storey parking near UniLodge - Davey Lodge",
    category: "Resident / private",
    lat: -35.27706,
    lng: 149.12418,
    hours: "Private access; permit required at all times.",
    rate: "Private access. Resident permit $4.90/day (2026) where applicable; otherwise not public parking.",
    permit: "Private or resident permit.",
    fees: "OSM access: private. Fee: yes. Type: multi-storey.",
    notes: "Beside UniLodge - Davey Lodge. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-anu-college-of-law-building",
    name: "Surface parking near ANU College of Law - Building 5 Foyer",
    category: "Resident / private",
    lat: -35.28112,
    lng: 149.11929,
    hours: "Private access; permit required at all times.",
    rate: "Private access. Resident permit $4.90/day (2026) where applicable; otherwise not public parking.",
    permit: "Private or resident permit.",
    fees: "OSM access: private. Type: surface.",
    notes: "Beside ANU College of Law - Building 5 Foyer. 3 marked accessible bays. Mapped in OpenStreetMap.",
    capacity: 11,
  },
  {
    slug: "surface-parking-near-brian-anderson-building-115",
    name: "Surface parking near Brian Anderson Building - 115",
    category: "Resident / private",
    lat: -35.27469,
    lng: 149.1207,
    hours: "Private access; permit required at all times.",
    rate: "Private access. Resident permit $4.90/day (2026) where applicable; otherwise not public parking.",
    permit: "Private or resident permit.",
    fees: "OSM access: private. Type: surface.",
    notes: "Beside Brian Anderson Building - 115. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-building-70",
    name: "Surface parking near Building 70",
    category: "Resident / private",
    lat: -35.28569,
    lng: 149.11784,
    hours: "Private access; permit required at all times.",
    rate: "Private access. Resident permit $4.90/day (2026) where applicable; otherwise not public parking.",
    permit: "Private or resident permit.",
    fees: "OSM access: private. Type: surface.",
    notes: "Beside Building 70. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-building-70-2",
    name: "Surface parking near Building 70",
    category: "Resident / private",
    lat: -35.28593,
    lng: 149.11759,
    hours: "Private access; permit required at all times.",
    rate: "Private access. Resident permit $4.90/day (2026) where applicable; otherwise not public parking.",
    permit: "Private or resident permit.",
    fees: "OSM access: private. Type: surface.",
    notes: "Beside Building 70. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-d",
    name: "Surface parking near D",
    category: "Resident / private",
    lat: -35.27579,
    lng: 149.11528,
    hours: "Private access; permit required at all times.",
    rate: "Private access. Resident permit $4.90/day (2026) where applicable; otherwise not public parking.",
    permit: "Private or resident permit.",
    fees: "OSM access: private. Type: surface.",
    notes: "Beside D. asphalt surface. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-ian-potter-house",
    name: "Surface parking near Ian Potter House",
    category: "Resident / private",
    lat: -35.28346,
    lng: 149.12393,
    hours: "Private access; permit required at all times.",
    rate: "Private access. Resident permit $4.90/day (2026) where applicable; otherwise not public parking.",
    permit: "Private or resident permit.",
    fees: "OSM access: private. Type: surface.",
    notes: "Beside Ian Potter House. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-la-baguette",
    name: "Surface parking near La Baguette",
    category: "Resident / private",
    lat: -35.2822,
    lng: 149.12167,
    hours: "Private access; permit required at all times.",
    rate: "Private access. Resident permit $4.90/day (2026) where applicable; otherwise not public parking.",
    permit: "Private or resident permit.",
    fees: "OSM access: private. Type: surface.",
    notes: "Beside La Baguette. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-theatre-3",
    name: "Surface parking near Theatre 3",
    category: "Resident / private",
    lat: -35.28179,
    lng: 149.12216,
    hours: "Private access; permit required at all times.",
    rate: "Private access. Resident permit $4.90/day (2026) where applicable; otherwise not public parking.",
    permit: "Private or resident permit.",
    fees: "OSM access: private. Type: surface.",
    notes: "Beside Theatre 3. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-unilodge-davey-lodge",
    name: "Surface parking near UniLodge - Davey Lodge",
    category: "Resident / private",
    lat: -35.27807,
    lng: 149.12416,
    hours: "Private access; permit required at all times.",
    rate: "Private access. Resident permit $4.90/day (2026) where applicable; otherwise not public parking.",
    permit: "Private or resident permit.",
    fees: "OSM access: private. Type: surface.",
    notes: "Beside UniLodge - Davey Lodge. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-wright-hall",
    name: "Surface parking near Wright Hall",
    category: "Resident / private",
    lat: -35.27551,
    lng: 149.11562,
    hours: "Private access; permit required at all times.",
    rate: "Private access. Resident permit $4.90/day (2026) where applicable; otherwise not public parking.",
    permit: "Private or resident permit.",
    fees: "OSM access: private. Type: surface.",
    notes: "Beside Wright Hall. asphalt surface. Mapped in OpenStreetMap.",
  },
  {
    slug: "underground-parking-near-marie-reay-teaching-cen",
    name: "Underground parking near Marie Reay Teaching Centre",
    category: "Resident / private",
    lat: -35.27758,
    lng: 149.12044,
    hours: "Private access; permit required at all times.",
    rate: "Private access. Resident permit $4.90/day (2026) where applicable; otherwise not public parking.",
    permit: "Private or resident permit.",
    fees: "OSM access: private. Fee: yes. Type: underground.",
    notes: "Beside Marie Reay Teaching Centre. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-acton-early-childhood-centr",
    name: "Surface parking near Acton Early Childhood Centre - 1C",
    category: "Staff / student surface",
    lat: -35.2853,
    lng: 149.11706,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction.",
    notes: "Beside Acton Early Childhood Centre - 1C. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-alumni-relations-and-philan",
    name: "Surface parking near Alumni Relations & Philanthropy - 71",
    category: "Staff / student surface",
    lat: -35.28503,
    lng: 149.11757,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction.",
    notes: "Beside Alumni Relations & Philanthropy - 71. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-anu-college",
    name: "Surface parking near ANU College",
    category: "Staff / student surface",
    lat: -35.27371,
    lng: 149.12116,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside ANU College. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-anu-college-2",
    name: "Surface parking near ANU College",
    category: "Staff / student surface",
    lat: -35.2734,
    lng: 149.12057,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside ANU College. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-anu-college-of-law-building-6",
    name: "Surface parking near ANU College of Law - Building 6",
    category: "Staff / student surface",
    lat: -35.27981,
    lng: 149.11822,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside ANU College of Law - Building 6. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-anu-medical-school-2",
    name: "Surface parking near ANU Medical School",
    category: "Staff / student surface",
    lat: -35.2827,
    lng: 149.11358,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside ANU Medical School. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-anu-medical-school-3",
    name: "Surface parking near ANU Medical School",
    category: "Staff / student surface",
    lat: -35.2826,
    lng: 149.11375,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside ANU Medical School. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-building-140a",
    name: "Surface parking near Building 140A",
    category: "Staff / student surface",
    lat: -35.28235,
    lng: 149.11277,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Building 140A. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-building-143a",
    name: "Surface parking near Building 143A",
    category: "Staff / student surface",
    lat: -35.28138,
    lng: 149.11387,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Building 143A. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-building-1a",
    name: "Surface parking near Building 1A",
    category: "Staff / student surface",
    lat: -35.28354,
    lng: 149.11907,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Building 1A. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-building-35b-2",
    name: "Surface parking near Building 35B",
    category: "Staff / student surface",
    lat: -35.27363,
    lng: 149.11984,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction.",
    notes: "Beside Building 35B. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-building-3h",
    name: "Surface parking near Building 3H",
    category: "Staff / student surface",
    lat: -35.28198,
    lng: 149.11741,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Building 3H. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-building-58a",
    name: "Surface parking near Building 58A",
    category: "Staff / student surface",
    lat: -35.28315,
    lng: 149.11234,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Building 58A. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-building-58a-2",
    name: "Surface parking near Building 58A",
    category: "Staff / student surface",
    lat: -35.28298,
    lng: 149.11231,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Building 58A. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-building-71t",
    name: "Surface parking near Building 71T",
    category: "Staff / student surface",
    lat: -35.28531,
    lng: 149.11881,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Building 71T. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-building-71t-2",
    name: "Surface parking near Building 71T",
    category: "Staff / student surface",
    lat: -35.28532,
    lng: 149.11863,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Building 71T. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-burgmann-college",
    name: "Surface parking near Burgmann College",
    category: "Staff / student surface",
    lat: -35.27985,
    lng: 149.11378,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Burgmann College. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-burgmann-college-2",
    name: "Surface parking near Burgmann College",
    category: "Staff / student surface",
    lat: -35.28027,
    lng: 149.11446,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Burgmann College. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-chancelry-building",
    name: "Surface parking near Chancelry Building",
    category: "Staff / student surface",
    lat: -35.27986,
    lng: 149.12054,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Chancelry Building. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-chancelry-building-2",
    name: "Surface parking near Chancelry Building",
    category: "Staff / student surface",
    lat: -35.2805,
    lng: 149.1197,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Chancelry Building. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-chancelry-building-3",
    name: "Surface parking near Chancelry Building",
    category: "Staff / student surface",
    lat: -35.28015,
    lng: 149.11973,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Chancelry Building. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-fses-field-services-2",
    name: "Surface parking near FSES Field Services",
    category: "Staff / student surface",
    lat: -35.27779,
    lng: 149.11807,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside FSES Field Services. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-graduate-house",
    name: "Surface parking near Graduate House",
    category: "Staff / student surface",
    lat: -35.28397,
    lng: 149.11727,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Graduate House. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-gravity-wave-building-36b",
    name: "Surface parking near Gravity Wave Building - 36B",
    category: "Staff / student surface",
    lat: -35.27466,
    lng: 149.11767,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM access: permissive. Type: surface.",
    notes: "Beside Gravity Wave Building - 36B. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-griffin-wing",
    name: "Surface parking near Griffin Wing",
    category: "Staff / student surface",
    lat: -35.28057,
    lng: 149.11254,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction.",
    notes: "Beside Griffin Wing. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-hedly-bull-130",
    name: "Surface parking near Hedly Bull - 130",
    category: "Staff / student surface",
    lat: -35.28402,
    lng: 149.12005,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Hedly Bull - 130. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-hedly-bull-130-2",
    name: "Surface parking near Hedly Bull - 130",
    category: "Staff / student surface",
    lat: -35.28346,
    lng: 149.12039,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Hedly Bull - 130. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-hugh-ennor-building-117",
    name: "Surface parking near Hugh Ennor Building - 117",
    category: "Staff / student surface",
    lat: -35.28265,
    lng: 149.1164,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Hugh Ennor Building - 117. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-ian-potter-house-2",
    name: "Surface parking near Ian Potter House",
    category: "Staff / student surface",
    lat: -35.28353,
    lng: 149.12317,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Ian Potter House. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-jaeger-7",
    name: "Surface parking near Jaeger 7",
    category: "Staff / student surface",
    lat: -35.28361,
    lng: 149.11485,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Jaeger 7. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-john-carver-building-58c",
    name: "Surface parking near John Carver Building - 58C",
    category: "Staff / student surface",
    lat: -35.28301,
    lng: 149.1132,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside John Carver Building - 58C. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-john-xxiii-college",
    name: "Surface parking near John XXIII College",
    category: "Staff / student surface",
    lat: -35.27939,
    lng: 149.11451,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside John XXIII College. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-national-computational-infr",
    name: "Surface parking near National Computational Infrastructure - 143",
    category: "Staff / student surface",
    lat: -35.28138,
    lng: 149.11419,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside National Computational Infrastructure - 143. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-nceph-65",
    name: "Surface parking near NCEPH - 65",
    category: "Staff / student surface",
    lat: -35.2852,
    lng: 149.11623,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction.",
    notes: "Beside NCEPH - 65. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-nuclear-physics-building",
    name: "Surface parking near Nuclear Physics Building",
    category: "Staff / student surface",
    lat: -35.28286,
    lng: 149.11291,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Nuclear Physics Building. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-nuclear-physics-building-2",
    name: "Surface parking near Nuclear Physics Building",
    category: "Staff / student surface",
    lat: -35.28282,
    lng: 149.11324,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Nuclear Physics Building. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-nuclear-physics-building-3",
    name: "Surface parking near Nuclear Physics Building",
    category: "Staff / student surface",
    lat: -35.28307,
    lng: 149.11279,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Nuclear Physics Building. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-ohb-a",
    name: "Surface parking near OHB-A",
    category: "Staff / student surface",
    lat: -35.28473,
    lng: 149.11539,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside OHB-A. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-oliphant-building-60",
    name: "Surface parking near Oliphant Building - 60",
    category: "Staff / student surface",
    lat: -35.28383,
    lng: 149.11345,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Oliphant Building - 60. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-r-g-menzies-library",
    name: "Surface parking near R.G. Menzies Library",
    category: "Staff / student surface",
    lat: -35.28224,
    lng: 149.11858,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside R.G. Menzies Library. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-r-g-menzies-library-2",
    name: "Surface parking near R.G. Menzies Library",
    category: "Staff / student surface",
    lat: -35.28217,
    lng: 149.11774,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside R.G. Menzies Library. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-research-school-of-populato",
    name: "Surface parking near Research School of Populaton Health",
    category: "Staff / student surface",
    lat: -35.28332,
    lng: 149.11512,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Research School of Populaton Health. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-research-school-of-populato-2",
    name: "Surface parking near Research School of Populaton Health",
    category: "Staff / student surface",
    lat: -35.28313,
    lng: 149.11491,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Research School of Populaton Health. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-research-school-of-populato-3",
    name: "Surface parking near Research School of Populaton Health",
    category: "Staff / student surface",
    lat: -35.28316,
    lng: 149.11574,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Research School of Populaton Health. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-robertson-eucalyptus-greenh",
    name: "Surface parking near Robertson Eucalyptus Greenhouse",
    category: "Staff / student surface",
    lat: -35.27849,
    lng: 149.11804,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Robertson Eucalyptus Greenhouse. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-scholars-house-3l",
    name: "Surface parking near Scholars House - 3L",
    category: "Staff / student surface",
    lat: -35.28062,
    lng: 149.11783,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Scholars House - 3L. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-science-teaching-building",
    name: "Surface parking near Science Teaching Building",
    category: "Staff / student surface",
    lat: -35.27617,
    lng: 149.11706,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Science Teaching Building. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-sir-roland-wilson-building",
    name: "Surface parking near Sir Roland Wilson Building",
    category: "Staff / student surface",
    lat: -35.28499,
    lng: 149.12024,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Sir Roland Wilson Building. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-skaidrite-darius-building-1",
    name: "Surface parking near Skaidrite Darius Building - 108",
    category: "Staff / student surface",
    lat: -35.27531,
    lng: 149.12083,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Skaidrite Darius Building - 108. asphalt surface. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-south-pavilion-88",
    name: "Surface parking near South Pavilion - 88",
    category: "Staff / student surface",
    lat: -35.28112,
    lng: 149.11467,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside South Pavilion - 88. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-south-pavilion-88-2",
    name: "Surface parking near South Pavilion - 88",
    category: "Staff / student surface",
    lat: -35.28145,
    lng: 149.11531,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside South Pavilion - 88. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-south-pavilion-88-3",
    name: "Surface parking near South Pavilion - 88",
    category: "Staff / student surface",
    lat: -35.28068,
    lng: 149.11516,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside South Pavilion - 88. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-sres-geography-building",
    name: "Surface parking near SRES Geography Building",
    category: "Staff / student surface",
    lat: -35.27743,
    lng: 149.1165,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside SRES Geography Building. 2 marked accessible bays. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-toad-hall",
    name: "Surface parking near Toad Hall",
    category: "Staff / student surface",
    lat: -35.27585,
    lng: 149.12425,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Toad Hall. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-ursula-hall-laurus-wing",
    name: "Surface parking near Ursula Hall Laurus Wing",
    category: "Staff / student surface",
    lat: -35.2785,
    lng: 149.11349,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction.",
    notes: "Beside Ursula Hall Laurus Wing. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-winston-churchill-memorial-",
    name: "Surface parking near Winston Churchill Memorial Trust - 93",
    category: "Staff / student surface",
    lat: -35.28511,
    lng: 149.1188,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Permit parking in enforced hours. 2026 rates: staff surface $7.78/day, non-resident student $3.88/day.",
    permit: "Staff or student surface permit.",
    fees: "OSM records no access restriction. Type: surface.",
    notes: "Beside Winston Churchill Memorial Trust - 93. Mapped in OpenStreetMap.",
  },
  {
    slug: "acton-underhill-parking",
    name: "Acton Underhill parking",
    category: "Staff parking station",
    lat: -35.2866,
    lng: 149.11624,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "$9.59 / day (2026 staff parking-station rate).",
    permit: "Staff parking-station permit, or casual pay where signed.",
    fees: "OSM records no access restriction. Fee: yes. Type: underground.",
    notes: "Mapped in OpenStreetMap.",
  },
  {
    slug: "baldessin-car-park",
    name: "Baldessin Car Park",
    category: "Staff parking station",
    lat: -35.27951,
    lng: 149.12186,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "$9.59 / day (2026 staff parking-station rate).",
    permit: "Staff parking-station permit, or casual pay where signed.",
    fees: "OSM access: yes. Fee: yes. Type: multi-storey.",
    notes: "Mapped in OpenStreetMap.",
  },
  {
    slug: "city-west-carpark",
    name: "City West CarPark",
    category: "Staff parking station",
    lat: -35.27841,
    lng: 149.12535,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "$9.59 / day (2026 staff parking-station rate).",
    permit: "Staff parking-station permit, or casual pay where signed.",
    fees: "OSM access: yes. Fee: yes. Type: multi-storey.",
    notes: "Mapped in OpenStreetMap.",
  },
  {
    slug: "kambri-car-park",
    name: "Kambri Car Park",
    category: "Staff parking station",
    lat: -35.27642,
    lng: 149.12188,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "$9.59 / day (2026 staff parking-station rate).",
    permit: "Staff parking-station permit, or casual pay where signed.",
    fees: "OSM access: yes. Fee: yes. Type: underground.",
    notes: "Mapped in OpenStreetMap.",
    capacity: 300,
  },
  {
    slug: "multi-storey-parking-near-dickson-parking-buildi",
    name: "Multi-storey parking near Dickson Parking Building",
    category: "Staff parking station",
    lat: -35.27885,
    lng: 149.11252,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "$9.59 / day (2026 staff parking-station rate).",
    permit: "Staff parking-station permit, or casual pay where signed.",
    fees: "OSM access: yes. Fee: yes. Type: multi-storey.",
    notes: "Beside Dickson Parking Building. Mapped in OpenStreetMap.",
  },
  {
    slug: "underground-parking-near-fenner-hall-152",
    name: "Underground parking near Fenner Hall - 152",
    category: "Staff parking station",
    lat: -35.27652,
    lng: 149.12172,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "$9.59 / day (2026 staff parking-station rate).",
    permit: "Staff parking-station permit, or casual pay where signed.",
    fees: "OSM access: yes. Fee: yes. Type: underground.",
    notes: "Beside Fenner Hall - 152. concrete surface. Mapped in OpenStreetMap.",
    capacity: 200,
  },
  {
    slug: "underground-parking-near-fenner-hall-152-2",
    name: "Underground parking near Fenner Hall - 152",
    category: "Staff parking station",
    lat: -35.2771,
    lng: 149.12122,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "$9.59 / day (2026 staff parking-station rate).",
    permit: "Staff parking-station permit, or casual pay where signed.",
    fees: "OSM access: yes. Fee: yes. Type: underground.",
    notes: "Beside Fenner Hall - 152. concrete surface. Mapped in OpenStreetMap.",
    capacity: 200,
  },
  {
    slug: "surface-parking-near-anu-college-of-law-building-2",
    name: "Surface parking near ANU College of Law - Building 6A - Moot Court",
    category: "Visitor pay parking",
    lat: -35.27954,
    lng: 149.11904,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Casual PayStay, charged by the hour up to a daily cap.",
    permit: "None — anyone may pay and park.",
    fees: "OSM access: yes. Fee: yes. Type: surface.",
    notes: "Beside ANU College of Law - Building 6A - Moot Court. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-baldessin-precinct-building",
    name: "Surface parking near Baldessin Precinct Building (BPB)",
    category: "Visitor pay parking",
    lat: -35.28056,
    lng: 149.12108,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Casual PayStay, charged by the hour up to a daily cap.",
    permit: "None — anyone may pay and park.",
    fees: "OSM access: yes. Fee: yes. Type: surface.",
    notes: "Beside Baldessin Precinct Building (BPB). Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-baldessin-precinct-building-2",
    name: "Surface parking near Baldessin Precinct Building (BPB)",
    category: "Visitor pay parking",
    lat: -35.27991,
    lng: 149.12247,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Casual PayStay, charged by the hour up to a daily cap.",
    permit: "None — anyone may pay and park.",
    fees: "OSM access: yes. Fee: yes. Type: surface.",
    notes: "Beside Baldessin Precinct Building (BPB). Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-birch-building-35",
    name: "Surface parking near Birch Building - 35",
    category: "Visitor pay parking",
    lat: -35.27381,
    lng: 149.11861,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Casual PayStay, charged by the hour up to a daily cap.",
    permit: "None — anyone may pay and park.",
    fees: "OSM access: yes. Fee: yes. Type: surface.",
    notes: "Beside Birch Building - 35. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-bruce-hall-packard-wing-40a",
    name: "Surface parking near Bruce Hall (Packard Wing) - 40A",
    category: "Visitor pay parking",
    lat: -35.27339,
    lng: 149.11806,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Casual PayStay, charged by the hour up to a daily cap.",
    permit: "None — anyone may pay and park.",
    fees: "OSM access: yes. Fee: yes. Type: surface.",
    notes: "Beside Bruce Hall (Packard Wing) - 40A. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-building-35b",
    name: "Surface parking near Building 35B",
    category: "Visitor pay parking",
    lat: -35.27375,
    lng: 149.11928,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Casual PayStay, charged by the hour up to a daily cap.",
    permit: "None — anyone may pay and park.",
    fees: "OSM access: yes. Fee: yes. Type: surface.",
    notes: "Beside Building 35B. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-college-of-business-and-eco",
    name: "Surface parking near College of Business and Economics - 26C",
    category: "Visitor pay parking",
    lat: -35.27639,
    lng: 149.12286,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Casual PayStay, charged by the hour up to a daily cap.",
    permit: "None — anyone may pay and park.",
    fees: "OSM access: yes. Fee: yes. Type: surface.",
    notes: "Beside College of Business and Economics - 26C. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-drill-hall-gallery-29",
    name: "Surface parking near Drill Hall Gallery - 29",
    category: "Visitor pay parking",
    lat: -35.2761,
    lng: 149.12329,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Casual PayStay, charged by the hour up to a daily cap.",
    permit: "None — anyone may pay and park.",
    fees: "OSM access: yes. Fee: yes. Type: surface.",
    notes: "Beside Drill Hall Gallery - 29. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-goodstart-early-learning-14",
    name: "Surface parking near Goodstart Early Learning - 147",
    category: "Visitor pay parking",
    lat: -35.27454,
    lng: 149.12143,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Casual PayStay, charged by the hour up to a daily cap.",
    permit: "None — anyone may pay and park.",
    fees: "OSM access: yes. Fee: yes. Type: surface.",
    notes: "Beside Goodstart Early Learning - 147. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-health-and-well-being-centr",
    name: "Surface parking near Health and Well-Being Centre",
    category: "Visitor pay parking",
    lat: -35.27685,
    lng: 149.11952,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Casual PayStay, charged by the hour up to a daily cap.",
    permit: "None — anyone may pay and park.",
    fees: "OSM access: yes. Fee: yes. Type: surface.",
    notes: "Beside Health and Well-Being Centre. asphalt surface. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-john-curtin-school-medical-",
    name: "Surface parking near John Curtin School Medical Research",
    category: "Visitor pay parking",
    lat: -35.28246,
    lng: 149.11513,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Casual PayStay, charged by the hour up to a daily cap.",
    permit: "None — anyone may pay and park.",
    fees: "OSM access: yes. Fee: yes. Type: surface.",
    notes: "Beside John Curtin School Medical Research. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-national-film-and-sound-arc",
    name: "Surface parking near National Film & Sound Archive",
    category: "Visitor pay parking",
    lat: -35.28271,
    lng: 149.1219,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Casual PayStay, charged by the hour up to a daily cap.",
    permit: "None — anyone may pay and park.",
    fees: "OSM access: yes. Fee: yes. Type: surface.",
    notes: "Beside National Film & Sound Archive. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-old-canberra-house-tennis-c",
    name: "Surface parking near Old Canberra House Tennis Court",
    category: "Visitor pay parking",
    lat: -35.28814,
    lng: 149.11749,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Casual PayStay, charged by the hour up to a daily cap.",
    permit: "None — anyone may pay and park.",
    fees: "OSM access: yes. Fee: yes. Type: surface.",
    notes: "Beside Old Canberra House Tennis Court. paved surface. 2 marked accessible bays. Mapped in OpenStreetMap.",
    capacity: 56,
  },
  {
    slug: "surface-parking-near-research-school-of-chemistr",
    name: "Surface parking near Research School of Chemistry",
    category: "Visitor pay parking",
    lat: -35.27664,
    lng: 149.11906,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Casual PayStay, charged by the hour up to a daily cap.",
    permit: "None — anyone may pay and park.",
    fees: "OSM access: yes. Fee: yes. Type: surface.",
    notes: "Beside Research School of Chemistry. asphalt surface. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-robertson-banksia-greenhous",
    name: "Surface parking near Robertson Banksia Greenhouse",
    category: "Visitor pay parking",
    lat: -35.27921,
    lng: 149.11708,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Casual PayStay, charged by the hour up to a daily cap.",
    permit: "None — anyone may pay and park.",
    fees: "OSM access: yes. Fee: yes. Type: surface.",
    notes: "Beside Robertson Banksia Greenhouse. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-school-of-art",
    name: "Surface parking near School of Art",
    category: "Visitor pay parking",
    lat: -35.28065,
    lng: 149.12161,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Casual PayStay, charged by the hour up to a daily cap.",
    permit: "None — anyone may pay and park.",
    fees: "OSM access: yes. Fee: yes. Type: surface.",
    notes: "Beside School of Art. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-school-of-art-2",
    name: "Surface parking near School of Art",
    category: "Visitor pay parking",
    lat: -35.28148,
    lng: 149.1212,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Casual PayStay, charged by the hour up to a daily cap.",
    permit: "None — anyone may pay and park.",
    fees: "OSM access: yes. Fee: yes. Type: surface.",
    notes: "Beside School of Art. Mapped in OpenStreetMap.",
  },
  {
    slug: "surface-parking-near-sports-union-extension-19a",
    name: "Surface parking near Sports Union Extension - 19a",
    category: "Visitor pay parking",
    lat: -35.27518,
    lng: 149.12143,
    hours: "Enforced 8:00am–5:00pm Mon–Fri. Free after 5pm and on weekends.",
    rate: "Casual PayStay, charged by the hour up to a daily cap.",
    permit: "None — anyone may pay and park.",
    fees: "OSM access: yes. Fee: yes. Type: surface.",
    notes: "Beside Sports Union Extension - 19a. Mapped in OpenStreetMap.",
  },
];
